import Head from "next/head";
import React from "react";
import Card from "../../components/Card";
import Cta from "../../components/Cta";
import Div from "../../components/Div";
import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";
import SectionHeading from "../../components/SectionHeading";
import Spacing from "../../components/Spacing";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { useRouter } from "next/router";

export async function getStaticProps() {
  const expertiseDirectory = path.join(process.cwd(), "content", "expertises", "fr");
  const filenames = fs.readdirSync(expertiseDirectory);

  const services = filenames.map((filename) => {
    const filePath = path.join(expertiseDirectory, filename);
    const fileContents = fs.readFileSync(filePath, "utf8");
    const { data } = matter(fileContents);

    return {
      id: data.slug,
      href: `/service/${data.slug || path.parse(filename).name}`,
      title: data.title || "Titre par défaut",
      subtitle: data.description || "Sous-titre par défaut",
      imgHome: data.imgHome || "/images/service_7.jpeg",
      description: data.description || "Description par défaut",
    };
  });

  return {
    props: {
      services,
    },
  };
}

export default function Expertise({ services }) {
  const router = useRouter();
  const { locale } = router;

  return (
    <>
      <Head>
        <title>Mes Expertises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <PageHeading title="Mes Expertises" bgSrc="/images/contact_hero_bg.jpeg" pageLinkText="Services" /> */}
        <Spacing lg="150" md="80" />
        <Div className="cs-shape_wrap_4">
          <Div className="cs-shape_4"></Div>
          <Div className="cs-shape_4"></Div>
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-4">
                <SectionHeading title="Toute mon expertise à votre service" subtitle="Artistes & Labels" />
                <Spacing lg="90" md="45" />
              </Div>
              <Div className="col-xl-8">
                <Div className="row">
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title="Gestion des droits d’auteur"
                      link={`/${locale}/expertise/droits-auteur`}
                      src="/images/droit-auteur/Home-PHOTODROITSDAUTEUR.JPG"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title="Gestion des droits voisins"
                      link={`/${locale}/expertise/droits-voisins`}
                      src="/images/droit-voisin/Home-Photodroitsvoisins.JPG"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title="Gestion administrative et éditoriale"
                      link={`/${locale}/expertise/gestion-administrative-et-editoriale`}
                      src="/images/gestion-admin/Home-PhotoGestionEditoriale.JPG"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title="Gestion des dossiers de subvention"
                      link={`/${locale}/expertise/dossier-subvention`}
                      src="/images/subvention/Home-GestionSubventions.JPG"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title="Gestion de la distribution physique et digitale"
                      link={`/${locale}/expertise/gestion-distribution`}
                      src="/images/gestion-distrib/Home-PhotoGestionDistrib.JPG"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title="Gestion des oeuvres en sous-édition"
                      link={`/${locale}/expertise/sous-edition`}
                      src="/images/sous-edition/Home-PhotoGestionSoused.JPG"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                </Div>
              </Div>
            </Div>
          </Div>
        </Div>

        <Spacing lg="150" md="80" />
        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="De la musique <br /> pour vos <i>images</i> ? "
            btnText="cliquez ici"
            btnLink="https://www.parigomusic.com/"
            bgSrc="/images/home/couverture-vaisseau.png"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
