import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Button from "../../components/Button";
import Cta from "../../components/Cta";
import Div from "../../components/Div";
import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";
import SectionHeading from "../../components/SectionHeading";
import Spacing from "../../components/Spacing";

export async function getStaticProps({ params, locale }) {
  const data = require(`../../lang/${locale}.json`);
  const albums = data.portfolio;
  const albumIndex = albums.findIndex((item) => item.slug === params.portfolioId);

  if (!albums || albumIndex === -1) {
    return { notFound: true };
  }

  const prevAlbum = albums[albumIndex - 1] || null;
  const nextAlbum = albums[albumIndex + 1] || null;

  return { props: { album: albums[albumIndex], prevAlbum, nextAlbum } };
}

export async function getStaticPaths() {
  // Charger les données pour chaque langue
  const frAlbums = require("../../lang/fr.json").portfolio;
  const enAlbums = require("../../lang/en.json").portfolio;

  // Générer les chemins pour chaque album dans chaque langue
  const paths = [
    ...frAlbums.map((album) => ({ params: { portfolioId: album.slug }, locale: "fr" })),
    ...enAlbums.map((album) => ({ params: { portfolioId: album.slug }, locale: "en" })),
  ];

  return { paths, fallback: false };
}

export default function PortfolioDetails({ album, prevAlbum, nextAlbum }) {
  return (
    <>
      <Head>
        <title>Portfolio - {album.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading title="Portfolio Details" bgSrc="/images/service_hero_bg.jpeg" pageLinkText={album.title} />
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="cs-page_navigation cs-center">
            <img src={album.src} alt="Details" className="cs-radius_15 w-20" />
          </Div>
          <Spacing lg="90" md="40" />
          <Div className="row">
            <Div className="col-lg-6">
              <SectionHeading title="Graffiti wall artwork" subtitle="Creative">
                <Spacing lg="40" md="20" />
                <p>
                  {album.description.split("\n").map((line, index) => (
                    <React.Fragment key={index}>
                      {line}
                      <br />
                    </React.Fragment>
                  ))}
                </p>
              </SectionHeading>
            </Div>

            <Div className="col-lg-5 offset-lg-1">
              <Spacing lg="60" md="40" />
              <h2 className="cs-font_30 cs-font_26_sm cs-m0">Project Info -</h2>
              <Spacing lg="50" md="30" />
              <Div className="row">
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">Category:</h3>
                  <p className="cs-m0">{album.category}</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">Genre:</h3>
                  <p className="cs-m0">{album.genre}</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">Date de sortie:</h3>
                  <p className="cs-m0">{album.releaseDate}</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">Dated:</h3>
                  <p className="cs-m0">14-Aug-2022</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">Client:</h3>
                  <p className="cs-m0">Andreo Bowla</p>
                  <Spacing lg="30" md="30" />
                </Div>
              </Div>
            </Div>
          </Div>
          <Spacing lg="65" md="10" />
          <Div className="cs-page_navigation cs-center">
            {prevAlbum && (
              <Div>
                <Button btnLink={`/portfolio/${prevAlbum.slug}`} btnText="Prev Project" variant="cs-type1" />
              </Div>
            )}
            {nextAlbum && (
              <Div>
                <Button btnLink={`/portfolio/${nextAlbum.slug}`} btnText="Next Project" />
              </Div>
            )}
          </Div>
        </Div>
        <Spacing lg="145" md="80" />
        <Cta title="agency@arino.com" bgSrc="/images/cta_bg_2.jpeg" variant="rounded-0" />
      </Layout>
    </>
  );
}
