import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Accordion from "../../components/Accordion";
import Button from "../../components/Button";
import Cta from "../../components/Cta";
import Div from "../../components/Div";
import IconBox from "../../components/IconBox";
import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";
import SectionHeading from "../../components/SectionHeading";
import TestimonialSlider from "../../components/Slider/TestimonialSlider";
import Spacing from "../../components/Spacing";

export default function ServiceDetails() {
	const router = useRouter();
	const serviceId = router.query.serviceId;
	return (
		<>
			<Head>
				<title>Service - {serviceId}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<PageHeading title="Détails du Service" bgSrc="/images/service_hero_bg.jpeg" pageLinkText={serviceId} />
				<Spacing lg="145" md="80" />
				<Div className="container">
					<SectionHeading
						title="Processus de gestion des droits"
						subtitle="Gestion des Droits d'Auteur"
						variant="cs-style1 text-center"
					/>
					<Spacing lg="90" md="45" />
					<Div className="row">
						<Div className="col-lg-4">
							<IconBox
								icon="/images/icons/service_icon_1.svg"
								title="Identification"
								subtitle="Identification des œuvres et des ayants droit, suivi des licences et des contrats."
							/>
							<Spacing lg="30" md="30" />
						</Div>
						<Div className="col-lg-4">
							<IconBox
								icon="/images/icons/service_icon_2.svg"
								title="Monétisation"
								subtitle="Stratégies pour maximiser les revenus générés par les droits d'auteur."
							/>
							<Spacing lg="30" md="30" />
						</Div>
						<Div className="col-lg-4">
							<IconBox
								icon="/images/icons/service_icon_3.svg"
								title="Protection"
								subtitle="Mise en place de mesures pour protéger les œuvres et les droits d'auteur."
							/>
							<Spacing lg="30" md="30" />
						</Div>
					</Div>
				</Div>
				<Spacing lg="120" md="50" />
				<Div className="container">
					<Div className="row align-items-center">
						<Div className="col-xl-5 col-lg-6">
							<Div className="cs-radius_15 cs-shine_hover_1">
								<img src="/images/service_img_1.jpeg" alt="Service" className="cs-radius_15 w-100" />
							</Div>
							<Spacing lg="0" md="40" />
						</Div>
						<Div className="col-lg-6 offset-xl-1">
							<h2 className="cs-font_50 cs-m0">Nos services les plus demandés</h2>
							<Spacing lg="50" md="30" />
							<Div className="row">
								<Div className="col-lg-6">
									<Button
										btnLink="/service/service-details"
										btnText="Gestion des licences"
										variant="cs-type2"
									/>
									<Spacing lg="20" md="10" />
									<Button
										btnLink="/service/service-details"
										btnText="Audit des droits"
										variant="cs-type2"
									/>
									<Spacing lg="20" md="10" />
								</Div>
								<Div className="col-lg-6">
									<Button
										btnLink="/service/service-details"
										btnText="Conseil en production"
										variant="cs-type2"
									/>
									<Spacing lg="20" md="10" />
									<Button
										btnLink="/service/service-details"
										btnText="Obtention de subventions"
										variant="cs-type2"
									/>
									<Spacing lg="20" md="10" />
								</Div>
							</Div>
						</Div>
					</Div>
				</Div>
				<Spacing lg="150" md="80" />
				<TestimonialSlider />
				<Spacing lg="145" md="80" />
				<Div className="container cs-shape_wrap_4">
					<Div className="cs-shape_4"></Div>
					<Div className="cs-shape_4"></Div>
					<Div className="container">
						<Div className="row">
							<Div className="col-xl-5 col-lg-6">
								<SectionHeading title="Questions fréquentes" subtitle="FAQ" />
								<Spacing lg="90" md="45" />
							</Div>
							<Div className="col-lg-6 offset-xl-1">
								<Accordion />
							</Div>
						</Div>
					</Div>
				</Div>
				<Spacing lg="150" md="80" />
				<Div className="container">
					<Cta
						title="Discutons ensemble de votre <br />projet <i>créatif</i>"
						btnText="Prendre rendez-vous"
						btnLink="/contact"
						bgSrc="/images/cta_bg.jpeg"
					/>
				</Div>
			</Layout>
		</>
	);
}
