import Head from "next/head";
import React from "react";
import Card from "../../components/Card";
import Cta from "../../components/Cta";
import Div from "../../components/Div";
import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";
import PricingTableList from "../../components/PricingTable/PricingTableList";
import SectionHeading from "../../components/SectionHeading";
import TestimonialSlider from "../../components/Slider/TestimonialSlider";
import Spacing from "../../components/Spacing";

export default function Service() {
	return (
		<>
			<Head>
				<title>Service</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<PageHeading title="Services" bgSrc="images/service_hero_bg.jpeg" pageLinkText="Services" />
				<Spacing lg="150" md="80" />
				<Div className="cs-shape_wrap_4">
					<Div className="cs-shape_4"></Div>
					<Div className="cs-shape_4"></Div>
					<Div className="container">
						<Div className="row">
							<Div className="col-xl-4">
								<SectionHeading
									title="Mon expertise <br />à votre service"
									subtitle="Artistes & Labels"
								/>
								<Spacing lg="90" md="45" />
							</Div>
							<Div className="col-xl-8">
								<Div className="row">
									<Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
									<Div className="col-lg-3 col-sm-6">
										<Card
											title="Gestion des droits d’auteur"
											link="/service/ui-ux-design"
											src="/images/service_1.jpeg"
											alt="Service"
										/>
										<Spacing lg="0" md="30" />
									</Div>
									<Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
									<Div className="col-lg-3 col-sm-6">
										<Card
											title="Production musicale"
											link="/service/reactjs-development"
											src="/images/service_2.jpeg"
											alt="Service"
										/>
										<Spacing lg="0" md="30" />
									</Div>
									<Div className="col-lg-3 col-sm-6">
										<Card
											title="Obtention de subventions"
											link="/service/digital-marketing"
											src="/images/service_3.jpeg"
											alt="Service"
										/>
										<Spacing lg="0" md="30" />
									</Div>
									<Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
									<Div className="col-lg-3 col-sm-6">
										<Card
											title="Musique à l’image"
											link="/service/technology"
											src="/images/service_4.jpeg"
											alt="Service"
										/>
										<Spacing lg="0" md="30" />
									</Div>
									<Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
									<Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
									<Div className="col-lg-3 col-sm-6">
										<Card
											title="Consultation en droits d’auteur"
											link="/service/consultancy"
											src="/images/service_5.jpeg"
											alt="Service"
										/>
										<Spacing lg="0" md="30" />
									</Div>
									<Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
									<Div className="col-lg-3 col-sm-6">
										<Card
											title="Droits d’auteur à l’international"
											link="/service/creative-design"
											src="/images/service_6.jpeg"
											alt="Service"
										/>
										<Spacing lg="0" md="30" />
									</Div>
								</Div>
							</Div>
						</Div>
					</Div>
				</Div>
				<Spacing lg="125" md="55" />
				<TestimonialSlider />
				<Spacing lg="150" md="80" />
				<Div className="container">
					<Cta
						title="Discutons et créons <br /> quelque chose de <i>grandiose</i> ensemble"
						btnText="Prendre un rendez-vous"
						btnLink="/contact"
						bgSrc="/images/cta_bg.jpeg"
					/>
				</Div>
			</Layout>
		</>
	);
}
