import Head from 'next/head';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact from '../components/FunFact';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import TeamSlider from '../components/Slider/TeamSlider';
import Spacing from '../components/Spacing';

export default function About() {
  const funfaceData = [
    {
      title: 'Clients Satisfaits',
      factNumber: '200',
    },
    {
      title: 'Projets Réalisés',
      factNumber: '150',
    },
    {
      title: 'Subventions Obtenues',
      factNumber: '50',
    },
    {
      title: 'Œuvres Protégées',
      factNumber: '300',
    },
  ];
  return (
    <>
      <Head>
        <title>Accueil - À propos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Début de la section d'en-tête */}
        <PageHeading
          title="À Propos de Moi"
          bgSrc="images/about_hero_bg.jpeg"
          pageLinkText="À Propos"
        />
        {/* Fin de la section d'en-tête */}

        {/* Début de la section À propos */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="Votre partenaire de confiance en droits d'auteur et production musicale"
                subtitle="À Propos de Moi"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                  Avec une expertise solide en droits d'auteur et en production musicale, je vous accompagne à chaque étape de votre projet artistique. Mon objectif est de sécuriser vos œuvres tout en maximisant leur potentiel.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-xl-2">
              <img
                src="/images/about_img_1.jpeg"
                alt="À Propos"
                className="w-100 cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
          </Div>
        </Div>
        <Spacing lg="75" md="55" />
        {/* Fin de la section À propos */}

        {/* Début de la section Faits Amusants */}
        <Div className="container">
          <FunFact
            title="Quelques chiffres"
            subtitle="Découvrez l'impact de mon travail à travers ces quelques statistiques."
            data={funfaceData}
          />
        </Div>
        {/* Fin de la section Faits Amusants */}

        {/* Début de la section Pourquoi me choisir */}
        <Spacing lg="100" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-image_layer cs-style1">
                <Div className="cs-image_layer_in">
                  <img
                    src="/images/about_img_4.jpeg"
                    alt="À Propos"
                    className="w-100 cs-radius_15"
                  />
                </Div>
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            <Div className="col-xl-5 offset-xl-1 col-lg-6">
              <SectionHeading
                title="Une expertise solide à votre service"
                subtitle="Pourquoi me choisir"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                  Mon approche personnalisée et mon expertise en droits d'auteur et en production musicale font de moi le partenaire idéal pour vos projets artistiques.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                  Je vous guide à travers les complexités juridiques et créatives, vous permettant de vous concentrer sur ce que vous faites de mieux : créer.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="0" />
              </SectionHeading>
            </Div>
          </Div>
        </Div>
        {/* Fin de la section Pourquoi me choisir */}

        {/* Début de la section Équipe */}
        {/* Vous pouvez supprimer cette section si elle n'est pas pertinente pour vous */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Une équipe formidable"
            subtitle="Notre Équipe"
            variant="cs-style1"
          />
          <Spacing lg="85" md="45" />
          <TeamSlider />
        </Div>
        {/* Fin de la section Équipe */}

        {/* Début de la section CTA */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Discutons et créons <br /> quelque chose de <i>grandiose</i> ensemble"
            btnText="Prendre un rendez-vous"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* Fin de la section CTA */}
      </Layout>
    </>
  );
}