import Head from "next/head";
import Cta from "../components/Cta";
import Div from "../components/Div";
import Layout from "../components/Layout";
import LogoList from "../components/LogoList";
import MovingText from "../components/MovingText";
import SectionHeading from "../components/SectionHeading";
import Spacing from "../components/Spacing";
import Hero3 from "../components/Hero/Hero3";
import ServiceList from "../components/ServiceList";
import { useState } from "react";
import Portfolio from "../components/Portfolio";
import { Icon } from "@iconify/react";
import VideoModal from "../components/VideoModal";
import ProjectSlider from "../components/Slider/ProjectSlider";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import fr from "../lang/fr.json";
import Accordion from "../components/Accordion";

export async function getStaticProps() {
  const expertiseDirectory = path.join(process.cwd(), "content", "expertises", "fr");
  const filenames = fs.readdirSync(expertiseDirectory);

  const expertises = filenames.map((filename) => {
    const filePath = path.join(expertiseDirectory, filename);
    const fileContents = fs.readFileSync(filePath, "utf8");
    const { data } = matter(fileContents);

    return {
      id: data.id,
      slug: data.slug,
      href: `/expertise/${data.slug || path.parse(filename).name}`,
      title: data.title || "Titre par défaut",
      subtitle: data.description || "Sous-titre par défaut",
      imgHome: data.imgHome || "/images/service_7.jpeg",
      description: data.description || "Description par défaut",
    };
  });

  return {
    props: {
      expertises,
    },
  };
}

export default function Home({ expertises }) {
  const [itemShow, setItemShow] = useState(6);

  const portfolioData = fr.portfolio;
  // console.log("portfolioData >>", portfolioData);

  // Hero Social Links
  const heroSocialLinks = [
    {
      name: "Parigo",
      links: "https://www.parigomusic.com/",
    },
    {
      name: "LinkedIn",
      links: "/",
    },
    {
      name: "Contact",
      links: "/contact",
    },
  ];

  const projetData = [
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_11.jpeg",
      category: "ui_ux_design",
    },
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_12.jpeg",
      category: "logo_design",
    },
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_13.jpeg",
      category: "web_design",
    },
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_14.jpeg",
      category: "mobile_apps",
    },
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_15.jpeg",
      category: "ui_ux_design",
    },
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_16.jpeg",
      category: "web_design",
    },
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_11.jpeg",
      category: "ui_ux_design",
    },
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_12.jpeg",
      category: "logo_design",
    },
    {
      title: "Colorful Art Work",
      subtitle: "See Details",
      href: "/portfolio/portfolio-details",
      src: "/images/portfolio_13.jpeg",
      category: "web_design",
    },
  ];

  return (
    <>
      <Head>
        <title>Home - Creative Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Hero Section */}
        <Hero3
          title="Caroline Senyk"
          subtitle="Production . Copyrigth . Publishing"
          socialLinksHeading=""
          heroSocialLinks={heroSocialLinks}
          bgImageUrl="./images/home/IMG_5273.JPG"
        />
        {/* End Hero Section */}
        {/* Start Expertises */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading title="Mes Expertises" subtitle="Services" variant="cs-style1 text-center" />
          <Spacing lg="70" md="45" />
          <ServiceList expertises={expertises} />
        </Div>
        {/* End Expertises */}

        {/* Début de la section Équipe */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading title="Derniers projets" subtitle="Sorties" variant="cs-style1" />
          <Spacing lg="85" md="45" />
          <ProjectSlider />
          <Spacing lg="85" md="45" />
        </Div>
        {/* Fin de la section Équipe */}

        {/* Start MovingText Section */}
        <Spacing lg="125" md="70" />
        <div>
          <MovingText text="Track Parigos de la semaine -" />
        </div>
        <Spacing lg="105" md="70" />
        {/* End MovingText Section */}

        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="De la musique <br /> pour vos <i>images</i> ? "
            btnText="cliquez ici"
            btnLink="https://www.parigomusic.com/"
            bgSrc="/images/home/couverture-vaisseau.png"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
